package com.openmeet.shared.data.storage;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Interface for extracting a specific Bean from a ResultSet.
 *
 * @see ResultSet
 * */
public interface ResultSetExtractor<B> {

    /**
     * Extracts the Bean from a ResultSet generated by a CRUD Query.
     *
     * @param resultSet the resultSet to extract the bean from
     * @return the Bean object extracted
     * */
    B extract(ResultSet resultSet) throws SQLException;

    /**
     * Returns a Bean from a resultSet generated by a Query JOIN.
     *
     * @param resultSet the resultSet to extract the bean from
     * @param resultClass the ResultSetExtractor Class to use to extract the Bean from the resultSet
     * @return the Bean extracted from the ResultSetExtractor
     * */
    default <T> Object extractIntoBean(ResultSet resultSet, Class<T> resultClass) throws NoSuchMethodException, InstantiationException, IllegalAccessException, SQLException, InvocationTargetException {
        Constructor classConstruct =  resultClass.getConstructor();

        ResultSetExtractor resultSetExtractor = (ResultSetExtractor) classConstruct.newInstance();

        return resultSetExtractor.extract(resultSet);
    }
}
